<a href="https://colab.research.google.com/github/Girija-Tandon/Python_Analysis/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a=np.array([2,3,4,5])
print(a)

[2 3 4 5]


In [ ]:
b = np.array([[3,4,6,7],[1,2,9,5]])
print(b)

[[3 4 6 7]
 [1 2 9 5]]


In [ ]:
c = np.array([[[3,4,6,7],[1,2,9,5],[23,45,12,78]]])
print(c)

[[[ 3  4  6  7]
  [ 1  2  9  5]
  [23 45 12 78]]]


In [ ]:
d = np.array([3,4,5],dtype=complex)
d

array([3.+0.j, 4.+0.j, 5.+0.j])

In [ ]:
np.arange(1,12,2).reshape(3,2)

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [ ]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
np.random.random((3,4))

array([[0.90573273, 0.35363683, 0.72747342, 0.96650172],
       [0.68288689, 0.54900398, 0.79561472, 0.18386354],
       [0.48089976, 0.98784189, 0.57105518, 0.24843158]])

In [ ]:
#np.linearly seoarable space
np.linspace(10,20,5)

array([10. , 12.5, 15. , 17.5, 20. ])

In [ ]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

Array Attribute


In [ ]:
a1 = np.arange(12,dtype=float).reshape(3,4)
a2 = np.arange(10,dtype=np.int32)
a3 = np.arange(8).reshape(2,2,2)

In [ ]:
#ndim
print(a1.ndim)

2


In [ ]:
#shape
print(a1.shape)
a1

(3, 4)


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
#size(number of element)
a3.size
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
#itemsize(memory occupied by element)(int32 = 4 byte , int64 and float = 8 byte)
a2.itemsize


4

In [ ]:
#dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

float64
int32
int64


Changing datatype


In [ ]:
#astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

Array Operation


In [ ]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

In [ ]:
#scalar operation
# arithmetic
a4 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [ ]:
#relational
a4 > 12

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
# vector operations
#arithmetic
a4 * a5

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

Array function



In [ ]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
#min/max/sum/prod
np.max(a4,axis=1)

array([ 3,  7, 11])

In [ ]:
#mean/median/std/var
np.mean(a4,axis=0)

array([4., 5., 6., 7.])

In [ ]:
#trigonometric function
np.sin(a4)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021]])

In [ ]:
#dot product
np.dot(a4,a5)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [ ]:
#log and exponents
np.log(a5)

array([[2.48490665, 2.56494936, 2.63905733],
       [2.7080502 , 2.77258872, 2.83321334],
       [2.89037176, 2.94443898, 2.99573227],
       [3.04452244, 3.09104245, 3.13549422]])

In [ ]:
#round/floor/ceil
np.floor(np.random.random((2,3))*100)

array([[90., 95.,  6.],
       [74., 55., 14.]])

Indexing and slicing


In [ ]:
a2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [ ]:
a2[-2]

np.int32(8)

In [ ]:
a1

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
a1[1,2]

np.float64(6.0)

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3[0,1,0]

np.int64(2)

In [ ]:
a3[1,1,0]

np.int64(6)

In [ ]:
a2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [ ]:
a2[2:5:2]

array([2, 4], dtype=int32)

In [ ]:
a1

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
a1[0,:]

array([0., 1., 2., 3.])

In [ ]:
a1[:,3]

array([ 3.,  7., 11.])

In [ ]:
a1[1:,1:3]

array([[ 5.,  6.],
       [ 9., 10.]])

In [ ]:
a1[::2,1::2]

array([[ 1.,  3.],
       [ 9., 11.]])

In [ ]:
a1[1::2,0::3]

array([[4., 7.]])

In [ ]:
a1[0:2,1:]

array([[1., 2., 3.],
       [5., 6., 7.]])

In [ ]:
a1[0:2,1::2]

array([[1., 3.],
       [5., 7.]])

In [ ]:
a6 = np.arange(27).reshape(3,3,3)
a6

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a6[1,:,:]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
a6[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a6[0,1]

array([3, 4, 5])

In [ ]:
a6[1,:,1]

array([10, 13, 16])

In [ ]:
a6[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [ ]:
a6[::2,0,0::2]

array([[ 0,  2],
       [18, 20]])

Iterative


In [ ]:
a1
for i in a1:
  print(i)

[0. 1. 2. 3.]
[4. 5. 6. 7.]
[ 8.  9. 10. 11.]


In [ ]:
a2
for i in a2:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
a3
for i in a3:
  print(i)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [ ]:
for i in np.nditer(a2):
  print(a2)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


Reshaping


In [ ]:
#transpose
np.transpose(a1)
a1.T

array([[ 0.,  4.,  8.],
       [ 1.,  5.,  9.],
       [ 2.,  6., 10.],
       [ 3.,  7., 11.]])

In [ ]:
#ravel()->(make in 1D array)
a1.ravel()

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

Stacking


In [ ]:
#Horizontal()->[2row,4col]
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
#vertical()
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Splitting


In [ ]:
#horizontal Splitting
np.hsplit(a5,2)

[array([[12, 13],
        [16, 17],
        [20, 21]]),
 array([[14, 15],
        [18, 19],
        [22, 23]])]

In [ ]:
#vertical Splitting
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]